Optional Feature Enchancments: flunkif and strip delimiters from values
larandvit/ebcdic-parser pull request #12
Opened 2024-06-14 10:11 UTC by vbdevpro

**Changes:** 

_1._ Added an optional layout field element "flunkif" that accepts a comma separated list of values that, if matched, excludes the entire record from the final output. Also, updated readme.md, engine rules manual documentation and example json speciifcation file. This currently only works with fixed length recrods. Work has started to include variable length layouts as well. 

_2._ Added an optional parameter to the run method (stripDelimiterValues) that strips the delimiter specified by the outputDelimiter from string field values on the input file. Also strip newline and carrige return characters in an attempt to "clean up" input data and limit parsing errors. Updated readme.md to document usage instructions.

2024-06-16 02:37 UTC, larandvit commented
Hi @vbdevpro,

Got your PR. I like stripDelimiterValues functionality. Let me some time, I want to run some tests.

Thank you.
Vitaly

2024-06-17 12:29 UTC, vbdevpro commented
> Hi @vbdevpro,
> 
> Got your PR. I like stripDelimiterValues functionality. Let me some time, I want to run some tests.
> 
> Thank you. Vitaly

OK. Thanks! I hope it adds something to your very useful library,

2024-06-24 02:19 UTC, larandvit requested changes
Hi Chris,
Can you please add stripdelimitervalues parameter to run it in CLI mode? When we run it in command line mode, it always runs as false for the parameter.

parser.add_argument("--stripdelimitervalues",nargs="?", default="yes" if ParameterDefaults.STRIP_DELIMITER_VALUES else "no", choices=["yes","no"], help="strip delimiter values", metavar='yes/no')

Thanks.

2024-06-24 11:55 UTC, vbdevpro commented
@larandvit Oh, right! Of course. Sorry about that. I will add.

2024-06-25 03:29 UTC, larandvit approved these changes

2024-06-25 03:29 UTC, merged

2024-06-25 03:30 UTC, larandvit commented
@vbdevpro 
The pull request has been merged.
Thank you!
Vitaly